### ISSUE TITLE
Upgrade postgres version to 10.x

### ISSUE THREAD

**Issue by barnabyalter** [NYULibraries/login#219]
@etgrieco We've been on 9.4.x which is the oldest still supported version. I'd like to see if we can jump to 10 without major consequences. We could prototype this in a container and then work out the issues before getting the new RDS resource form Sys. This would all be an iteration after moving to K8s though of course. Thanks!

**Comment by etgrieco** [comment]
@barnabyalter We can also update the postgres controller gem, which hasn't been touched in a long time, while we're at it. This is a good opportunity for that.

**Comment by barnabyalter** [comment]
Upgrading to 11.x per AWS RDS requirements: https://github.com/NYULibraries/login/commit/c92a9dd322495c22cd51a399ed54290316868485

Will update pg version at a later time
