### ISSUE TITLE
Better Aleph error handling

### ISSUE THREAD

**Issue by ericgriffis** [NYULibraries/login#230]
Don't fail when Aleph X Service is failing. Instead, use existing information if present, but log failures to Sentry.

**Comment by ericgriffis** [comment]
https://github.com/NYULibraries/login/blob/master/app/models/user.rb#L67-L77

**Comment by barnabyalter** [comment]
Done: https://github.com/NYULibraries/login/commit/8074eb5c8625444c2bf33fae8acf15e37e5466cd
